# Enhanced Photo Analyzer Configuration
# Optimized for better accuracy and simplified output

# Performance settings
max_workers: 8  # Number of parallel workers
batch_size: 50  # Number of files to process in each batch
cache_enabled: true  # Enable EXIF data caching
cache_dir: ~/.photo_analyzer_cache  # Cache directory
progress_file: ~/.photo_analyzer_progress.json  # Progress tracking file

# Claude AI settings (optional)
claude_analysis:
  enabled: true  # Enable Claude AI content analysis
  sample_size: 20  # Number of photos to analyze with Claude
  confidence_threshold: 8  # Minimum confidence for category override
  model: "claude-3-sonnet-20240229"  # Claude model to use

# Enhanced category definitions with improved accuracy
categories:
  Portrait:
    focal_range: [50, 135]  # Focal length range in mm
    f_number_max: 2.8  # Maximum f-number for portrait detection
    weight: 1.0  # Scoring weight multiplier
    confidence_threshold: 3.0  # Minimum score to classify as portrait
    
  Landscape:
    focal_range: [0, 35]  # Focal length range in mm
    f_number_min: 8  # Minimum f-number for landscape detection
    weight: 1.0  # Scoring weight multiplier
    confidence_threshold: 3.0  # Minimum score to classify as landscape
    
  Street:
    focal_range: [28, 50]  # Focal length range in mm
    weight: 1.0  # Scoring weight multiplier
    confidence_threshold: 3.0  # Minimum score to classify as street
    
  Event:
    burst_threshold: 5  # Minimum photos for burst detection
    weight: 1.0  # Scoring weight multiplier
    confidence_threshold: 2.0  # Lower threshold for events
    
  Wildlife:
    focal_range: [200, 999]  # Focal length range in mm
    weight: 1.0  # Scoring weight multiplier
    confidence_threshold: 3.0  # Minimum score to classify as wildlife
    
  Sports:
    focal_range: [200, 999]  # Focal length range in mm
    weight: 1.0  # Scoring weight multiplier
    confidence_threshold: 3.0  # Minimum score to classify as sports
    
  Macro:
    subject_distance_max: 50  # Maximum subject distance in cm
    weight: 1.0  # Scoring weight multiplier
    confidence_threshold: 4.0  # Higher threshold for macro (more specific)
    
  Architecture:
    focal_range: [0, 24]  # Focal length range in mm
    weight: 1.0  # Scoring weight multiplier
    confidence_threshold: 3.0  # Minimum score to classify as architecture
    
  Night:
    iso_min: 1600  # Minimum ISO for night detection
    weight: 1.0  # Scoring weight multiplier
    confidence_threshold: 3.0  # Minimum score to classify as night

# Output settings
output:
  create_simplified_report: true  # Generate simplified summary report
  create_json_summary: true  # Generate simplified JSON summary
  include_claude_analysis: true  # Include Claude analysis in output
  max_mismatch_samples: 50  # Maximum number of mismatch examples to include

# Advanced settings
advanced:
  confidence_threshold: 3.0  # Global confidence threshold
  burst_time_threshold: 1.0  # Time threshold for burst detection (seconds)
  enable_negative_scoring: true  # Enable negative scoring for better accuracy
  prioritize_claude_for_uncategorized: true  # Use Claude for uncategorized photos 